### PR TITLE
Added release dates to changelog.

### LINKED ISSUE #115: Add release dates to changelog
We can get them all here:
https://libraries.io/npm/futil-js/versions

### PR DESCRIPTION
**Pull request by geosp**
Added release dates to change log. Fixes #115

### CODE REVIEW

**Comment by daedalus28** [comment]
Great stuff - but why is it inconsistent with some of them having timestamps/years and others not?

**Comment by decrapifier** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>Running your Dangerfile has Failed</td>
    </tr>
  </tbody>
</table>




## Danger has errored

Error: TypeError

```sh
TypeError: packageDiff.includes is not a function
    at Object.<anonymous> (dangerfile.js:28:41)
    at Runtime._execModule (/home/ubuntu/futil-js/node_modules/jest-runtime/build/index.js:447:13)
    at Runtime.requireModule (/home/ubuntu/futil-js/node_modules/jest-runtime/build/index.js:295:14)
    at /home/ubuntu/futil-js/node_modules/danger/distribution/runner/DangerfileRunner.js:136:33
    at ensureCleanDangerfile (/home/ubuntu/futil-js/node_modules/danger/distribution/runner/DangerfileRunner.js:176:5)
    at Object.<anonymous> (/home/ubuntu/futil-js/node_modules/danger/distribution/runner/DangerfileRunner.js:135:21)
    at step (/home/ubuntu/futil-js/node_modules/danger/distribution/runner/DangerfileRunner.js:32:23)
    at Object.next (/home/ubuntu/futil-js/node_modules/danger/distribution/runner/DangerfileRunner.js:13:53)
    at /home/ubuntu/futil-js/node_modules/danger/distribution/runner/DangerfileRunner.js:7:71
    at __awaiter (/home/ubuntu/futil-js/node_modules/danger/distribution/runner/DangerfileRunner.js:3:12)
```


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by decrapifier** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Running your Dangerfile has Failed
  </td>
    </tr>
  </tbody>
</table>




## Danger has errored

Error: Error

```sh
Error: Cannot find module 'package.json'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at getBabelRC (/home/ubuntu/futil-js/node_modules/babel-jest/build/index.js:53:41)
    at Object.getCacheKey (/home/ubuntu/futil-js/node_modules/babel-jest/build/index.js:90:14)
    at ScriptTransformer._getCacheKey (/home/ubuntu/futil-js/node_modules/jest-runtime/build/ScriptTransformer.js:68:26)
    at ScriptTransformer._getFileCachePath (/home/ubuntu/futil-js/node_modules/jest-runtime/build/ScriptTransformer.js:93:27)
    at ScriptTransformer.transformSource (/home/ubuntu/futil-js/node_modules/jest-runtime/build/ScriptTransformer.js:182:32)
    at ScriptTransformer._transformAndBuildScript (/home/ubuntu/futil-js/node_modules/jest-runtime/build/ScriptTransformer.js:275:40)
```


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by decrapifier** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Running your Dangerfile has Failed
  </td>
    </tr>
  </tbody>
</table>




## Danger has errored

Error: Error

```sh
Error: Cannot find module 'package.json'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at getBabelRC (/home/ubuntu/futil-js/node_modules/babel-jest/build/index.js:53:41)
    at Object.getCacheKey (/home/ubuntu/futil-js/node_modules/babel-jest/build/index.js:90:14)
    at ScriptTransformer._getCacheKey (/home/ubuntu/futil-js/node_modules/jest-runtime/build/ScriptTransformer.js:68:26)
    at ScriptTransformer._getFileCachePath (/home/ubuntu/futil-js/node_modules/jest-runtime/build/ScriptTransformer.js:93:27)
    at ScriptTransformer.transformSource (/home/ubuntu/futil-js/node_modules/jest-runtime/build/ScriptTransformer.js:182:32)
    at ScriptTransformer._transformAndBuildScript (/home/ubuntu/futil-js/node_modules/jest-runtime/build/ScriptTransformer.js:275:40)
```


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by decrapifier** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Running your Dangerfile has Failed
  </td>
    </tr>
  </tbody>
</table>




## Danger has errored

Error: SyntaxError

```sh
dangerfile.js:2
import _ from 'lodash/fp';
^^^^^^
SyntaxError: Unexpected token import
    at ScriptTransformer._transformAndBuildScript (/home/ubuntu/futil-js/node_modules/jest-runtime/build/ScriptTransformer.js:289:17)
    at ScriptTransformer.transform (/home/ubuntu/futil-js/node_modules/jest-runtime/build/ScriptTransformer.js:316:21)
    at Runtime._execModule (/home/ubuntu/futil-js/node_modules/jest-runtime/build/index.js:494:53)
    at Runtime.requireModule (/home/ubuntu/futil-js/node_modules/jest-runtime/build/index.js:329:14)
    at /home/ubuntu/futil-js/node_modules/danger/distribution/runner/DangerfileRunner.js:136:33
    at ensureCleanDangerfile (/home/ubuntu/futil-js/node_modules/danger/distribution/runner/DangerfileRunner.js:176:5)
    at Object.<anonymous> (/home/ubuntu/futil-js/node_modules/danger/distribution/runner/DangerfileRunner.js:135:21)
    at step (/home/ubuntu/futil-js/node_modules/danger/distribution/runner/DangerfileRunner.js:32:23)
    at Object.next (/home/ubuntu/futil-js/node_modules/danger/distribution/runner/DangerfileRunner.js:13:53)
    at /home/ubuntu/futil-js/node_modules/danger/distribution/runner/DangerfileRunner.js:7:71
```


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by decrapifier** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Running your Dangerfile has Failed
  </td>
    </tr>
  </tbody>
</table>




## Danger has errored

Error: Error

```sh
Error: Cannot find module 'package.json'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at getBabelRC (/home/ubuntu/futil-js/node_modules/babel-jest/build/index.js:53:41)
    at Object.getCacheKey (/home/ubuntu/futil-js/node_modules/babel-jest/build/index.js:90:14)
    at ScriptTransformer._getCacheKey (/home/ubuntu/futil-js/node_modules/jest-runtime/build/ScriptTransformer.js:68:26)
    at ScriptTransformer._getFileCachePath (/home/ubuntu/futil-js/node_modules/jest-runtime/build/ScriptTransformer.js:93:27)
    at ScriptTransformer.transformSource (/home/ubuntu/futil-js/node_modules/jest-runtime/build/ScriptTransformer.js:182:32)
    at ScriptTransformer._transformAndBuildScript (/home/ubuntu/futil-js/node_modules/jest-runtime/build/ScriptTransformer.js:275:40)
```


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Pull request merged**
