### PR TITLE
fix broken test, lint issue with _, and f -> F

### LINKED ISSUE #225: Fix CI
It seems like our master build is failing CI. Locally, it seems like it's due to something with eslint-plugin-mocha from eslint-config-smartprocure 🤔 

@sadasant any ideas?

### PR DESCRIPTION
**Pull request by daedalus28**
Fixes #225

No need for version bump because it blocked prior release

### CODE REVIEW

**Comment by decrapifier** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Danger failed to run `/home/circleci/project/node_modules/duti/src/dangerfile.js`.
  </td>
    </tr>
  </tbody>
</table>



## Error Error
```

Error
    at /home/circleci/project/node_modules/duti/src/utils.js:37:11
    at <anonymous>
```
### Dangerfile
```
32|       markdown: log(markdown),
33|       config,
34|       message: log(message),
35|       lintResults: await getLintResults({ config }),
36|       testResults: await getTestResults({ config }),
-------------^
37|       browserResults: await getBrowserResults({ config }),
38|     })
39|   )
40| })
```
  
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by hugomarisco** [comment]
Ah, I forgot to include `--require ./test/init.js` in all calls to `mocha` in `package.json` scripts. It essentially mocks the `__VERSION__` global that is provided by Webpack in a real scenario. Do you want me to create a PR to include it?

**Comment by daedalus28** [comment]
This could also be fixed by making the tests run against the _built_ version of the lib which is probably a good idea anyway. I think the reason we didn't do that before was that it complicated test coverage, but's probably a thing we should do

**Comment by daedalus28** [comment]
@hugomarisco sure, you can create a PR to this branch 😄

**Comment by hugomarisco** [comment]
@daedalus28 can I delete the test for the deprecated method `mapProp` as part of that commit? https://github.com/smartprocure/futil-js/blob/master/test/objects.spec.js#L184

it's making the tests/coverage fail

**Comment by daedalus28** [comment]
@hugomarisco just pushed a fix for that test to this branch

**Comment by daedalus28** [comment]
Also, as a general note - to respect semver, we're planning to leave every deprecated method in place until the next major version since that's a breaking change. Before inflicting that on users, we'd want to be sure there was enough of a positive addition to warrant the breaking change since we recognize that it can create real work for devs that depend on this library.

**Comment by hugomarisco** [comment]
Yes, that makes sense. I didn't read the code properly and I thought the logic for that method was already gone and that tests could also be removed.

**Comment by decrapifier** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Browser test error. Please see CI logs for more details.
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  The changelog has not been updated. Please update the changelog.
  </td>
    </tr>
  
<tr>
      <td>:no_entry_sign:</td>
      <td>

  The version was not updated. Please update the version.
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  You should add at least 1 more reviewer to the PR
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  Branch being merged does not follow [Git Flow](http://nvie.com/posts/a-successful-git-branching-model/)
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  The README has not been updated. Please update the README.
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  You reduced the total lines of code! Awesome! :+1:
  </td>
    </tr>
  </tbody>
</table>


<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Pull request merged**
