### PR TITLE
Adding circle.yml

### PR DESCRIPTION
**Pull request by sadasant**

### CODE REVIEW

**Comment by sadasant** [comment]
Here is how it worked: https://circleci.com/gh/smartprocure/futil-js/6?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link :)

**Comment by daedalus28** [comment]
If I merge this, both ci services will push to npm, wont they?

**Comment by sadasant** [comment]
@daedalus28 nope! It's commented: https://github.com/smartprocure/futil-js/pull/39/files#diff-29944324a3cbf9f4bd0162dfe3975d88R26

**Comment by sadasant** [comment]
@daedalus28 the main thing to see here is which one of both seems nicer, besides the pricing.

**Pull request merged**
