### PR TITLE
[WIP] setting up codeclimate coverage

### PR DESCRIPTION
**Pull request by sadasant**

### CODE REVIEW

**Comment by sadasant** [comment]
I think we still need this step to allow code coverage on PRs:

**Comment by sadasant** [comment]
@daedalus28 Sam! are you able to find this button in your account? I think we can make this work once it's active: https://github.com/smartprocure/futil-js/pull/24#issuecomment-281122905

**Comment by daedalus28** [comment]
I don't see a settings link on my account either :(

**Comment by sadasant** [comment]
I will write to codeclimate

**Comment by sadasant** [comment]
The last step to make codeclimate work is to make a PR changing https://github.com/codeclimate/codeclimate-eslint/edit/channel/eslint-3/package.json and generating a new shrinkwrap. I've been trying to generate it, but there are a bunch of invalid peers :/ I just wrote them about it.

**Comment by sadasant** [comment]
Code climate upgraded their eslint plugin for us! https://github.com/codeclimate/codeclimate-eslint/pull/190

**Comment by sadasant** [comment]
@daedalus28 turns out that we need to activate codeclimate's pull request integration from the admin account: https://docs.codeclimate.com/docs/github#pull-requests it needs to be done from the admin account

**Comment by daedalus28** [comment]
Sure, but this branch has conflicts and eslint issues. Also, generally the PR would have been merged by me, and I'm pretty sure I'm an admin - but we can try again 😄

**Comment by sadasant** [comment]
@daedalus28  no no, this PR breaks eslint intentionally! What we need from the admin account is to set up codeclimate integration with pull request, see the link! it's like a button on the repo settings or something, once we have that, we can see codeclimate also breaking this PR, then I can fix the _intentionally left_ eslint issue and we can talk about merging this.

**Comment by daedalus28** [comment]
Got it, but I don't see the settings button for the repos. Something is a bit funky here :(

**Comment by sadasant** [comment]
😅 darn

**Comment by daedalus28** [comment]
Closing because code climate's lack of proper eslint support is just to much effort to deal with

**Pull request closed without merging**
