### PR TITLE
New Documentation Site!

### PR DESCRIPTION
**Pull request by daedalus28**
# New Documentation Website!

The new docs site is packed with awesome features. We've got dark mode, super-fast search, embedded runkits, and the ability to search futil, lodash, and ramda based on input/output expectations.

This PR doesn't actually publish the site - that will be a follow up PR.

This is most of #111 

Enjoy these sizzle screenshots:

Screen Shot 2022-08-30 at 6 06 28 PM

Screen Shot 2022-08-30 at 5 59 41 PM

Screen Shot 2022-08-30 at 5 59 49 PM
Screen Shot 2022-08-30 at 6 00 03 PM
Screen Shot 2022-08-30 at 6 00 25 PM
Screen Shot 2022-08-30 at 6 00 38 PM
Screen Shot 2022-08-30 at 6 01 01 PM

### CODE REVIEW

**Comment by decrapifier** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>:exclamation: This PR is BIG (+1524 -4)  
Please keep it below 500 net changes</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>You should add at least 1 more reviewer to the PR</td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  Branch being merged does not follow [Git Flow](http://nvie.com/posts/a-successful-git-branching-model/)
  </td>
    </tr>
  </tbody>
</table>


<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Your PR has no browser errors. Great job!</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>We were able to automatically fix some formatting issues in this PR for you!</td>
    </tr>
  </tbody>
</table>

kill all humans


### Some things that were possibly fixed:

- Code that could be fixed via the --fix flag
- Formatting that could be fixed by prettier

Take a look at this commit to see what happened in detail: 5824369468a9ef13c7bc5f610314b543ca34ad97


And look at this wiki page to see the reasoning behind the ESLint rules: https://github.com/smartprocure/eslint-config-smartprocure/wiki/Rules-and-Why-We-Chose-Them
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 186debd2f6a8f5829066c6db7283f5c8fe7d2454
</p>

**Review by nico-olivares — APPROVED** [review]

**Comment by nico-olivares** [comment]
Looks great!

**Review by stellarhoof — COMMENTED** [review]
It's great to see this project finally reaching completion. Nice!

I've found a few things:

- There are lots of eslint warnings when the docs site is started
- Tooltips are unreadable because the text is black on the tooltip's dark background
- There are many deprecation warnings in the dev console

Also, what are service workers and web-vitals for?

**Comment by daedalus28** [comment]
> It's great to see this project finally reaching completion. Nice!
> 
> I've found a few things:
> 
> * There are lots of eslint warnings when the docs site is started
> * Tooltips are unreadable because the text is black on the tooltip's dark background
> * There are many deprecation warnings in the dev console
> 
> Also, what are service workers and web-vitals for?

- Good point on the lint issues, they're fixed now
- The deprecation warnings were caused by iterating over all of futil's methods including deprecated ones, but it's a good point that we shouldn't be suggesting deprecated methods. #369 will let me inspect and skip over those
- I haven't seen the tooltip issue myself, that's odd 🤔 I'll investigate further
- The files for service workers, web-vitals, the readme, etc were all out of the box generated by bootstrapping create-react-app. I'm not actually sure what they're for 🤔

**Comment by stellarhoof** [comment]
I still see the tooltip issue

image

Looks like it's fixed by https://github.com/chakra-ui/chakra-ui/pull/6611

**Review by stellarhoof — APPROVED** [review]
Let's go!!

**Pull request merged**
