### PR TITLE
Use onMouseEnter/Leave in domLens.hover

### PR DESCRIPTION
**Pull request by michsa**
`onMouseEnter`/`onMouseLeave` are more consistent with the notion of "hovering" state on a DOM element, since they don't bubble the cursor events to children. With `onMouseOver`/`onMouseOut`, hovering over a child of the element can interfere with the event, which is probably not the behavior we want for `domLens.hover`.

https://javascript.info/mousemove-mouseover-mouseout-mouseenter-mouseleave#mouseout-when-leaving-for-a-child

### CODE REVIEW

**Comment by decrapifier** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>This PR has failing tests. Please alleviate the errors and commit them

<details>
  <summary>hover</summary>
  <code>props.onMouseOver is not a function</code>
</details></td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Could not find any browser results.</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>We were able to automatically fix some formatting issues in this PR for you!</td>
    </tr>
  </tbody>
</table>


### Some things that were possibly fixed:

- Code that could be fixed via the --fix flag
- Formatting that could be fixed by prettier

Take a look at this commit to see what happened in detail: 2754300565ad0ff188c6d5cf4514f3e35c85978d


And look at this wiki page to see the reasoning behind the ESLint rules: https://github.com/smartprocure/eslint-config-smartprocure/wiki/Rules-and-Why-We-Chose-Them
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against 8b842980f3a5bd79e3a20fac2e1826d740200666
</p>

**Comment by stellarhoof** [comment]
Why are there so many formatting changes? Also, a failing test

**Comment by michsa** [comment]
@stellarhoof ask duti 🤔https://github.com/smartprocure/futil-js/pull/297/commits/2754300565ad0ff188c6d5cf4514f3e35c85978d

the test thing was dumb on my part - fixed

**Comment by decrapifier** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>Your PR has no browser errors. Great job!</td>
    </tr>
  
<tr>
      <td>:book:</td>
      <td>We were able to automatically fix some formatting issues in this PR for you!</td>
    </tr>
  </tbody>
</table>


### Some things that were possibly fixed:

- Code that could be fixed via the --fix flag
- Formatting that could be fixed by prettier

Take a look at this commit to see what happened in detail: 82ad3317936282c2fa33b76cb14b45581cd2d0ff


And look at this wiki page to see the reasoning behind the ESLint rules: https://github.com/smartprocure/eslint-config-smartprocure/wiki/Rules-and-Why-We-Chose-Them
<p align="right">
  Generated by :no_entry_sign: <a href="https://danger.systems/js">dangerJS</a> against c482ef67ec25fb7ec5cc558565474abb4765a274
</p>

**Pull request merged**
