### PR TITLE
Basic Async Utilities

### LINKED ISSUE #107: Implement an async flow
I think it can be like this:

```js
export let asyncFlow = (head, ...tail) => async (...params) => asyncFlow(...tail)(await head(...params))
```

### PR DESCRIPTION
**Pull request by daedalus28**
- Add Async methods: `flowAsync`, `flurryAsync`, `promisedProps`, `mapAsync`, `mapValuesAsync`
- Add `flatMapIndexed`, `throwsError`

Fixes #107

### CODE REVIEW

**Comment by decrapifier** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Fails</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:no_entry_sign:</td>
      <td>

  Your PR has 8 failed browser tests:

Suite: Async Functions
Description: mapAsync
Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
tryCatcher@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:19750:28
_settlePromiseFromHandler@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17772:35
_settlePromise@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17829:43
_settlePromise0@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17874:24
_settlePromises@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17953:33
_drainQueue@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:14682:31
_drainQueues@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:14692:21
drainQueues@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:14566:26
run@base/node_modules/babel-polyfill/dist/polyfill.js?03b9323c0501aae92009b27cf63cea3f4754b408:3911:29
base/node_modules/babel-polyfill/dist/polyfill.js?03b9323c0501aae92009b27cf63cea3f4754b408:3924:31
flush@base/node_modules/babel-polyfill/dist/polyfill.js?03b9323c0501aae92009b27cf63cea3f4754b408:1209:11


Suite: Async Functions
Description: mapValuesAsync
Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
tryCatcher@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:19750:28
_settlePromiseFromHandler@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17772:35
_settlePromise@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17829:43
_settlePromise0@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17874:24
_settlePromises@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17953:33
_drainQueue@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:14682:31
_drainQueues@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:14692:21
drainQueues@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:14566:26
run@base/node_modules/babel-polyfill/dist/polyfill.js?03b9323c0501aae92009b27cf63cea3f4754b408:3911:29
base/node_modules/babel-polyfill/dist/polyfill.js?03b9323c0501aae92009b27cf63cea3f4754b408:3924:31
flush@base/node_modules/babel-polyfill/dist/polyfill.js?03b9323c0501aae92009b27cf63cea3f4754b408:1209:11


Suite: Async Functions
Description: flowAsync
Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
tryCatcher@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:19750:28
_settlePromiseFromHandler@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17772:35
_settlePromise@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17829:43
_settlePromise0@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17874:24
_settlePromises@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17953:33
_drainQueue@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:14682:31
_drainQueues@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:14692:21
drainQueues@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:14566:26
promiseReactionJob@[native code]


Suite: Async Functions
Description: mapAsync
Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
tryCatcher@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:19750:28
_settlePromiseFromHandler@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17772:35
_settlePromise@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17829:43
_settlePromise0@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17874:24
_settlePromises@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17953:33
_drainQueue@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:14682:31
_drainQueues@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:14692:21
drainQueues@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:14566:26
promiseReactionJob@[native code]


Suite: Async Functions
Description: mapValuesAsync
Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
tryCatcher@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:19750:28
_settlePromiseFromHandler@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17772:35
_settlePromise@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17829:43
_settlePromise0@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17874:24
_settlePromises@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17953:33
_drainQueue@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:14682:31
_drainQueues@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:14692:21
drainQueues@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:14566:26
promiseReactionJob@[native code]


Suite: Async Functions
Description: flurryAsync
Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
tryCatcher@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:19750:28
_settlePromiseFromHandler@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17772:35
_settlePromise@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17829:43
_settlePromise0@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17874:24
_settlePromises@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17953:33
_drainQueue@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:14682:31
_drainQueues@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:14692:21
drainQueues@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:14566:26
run@base/node_modules/babel-polyfill/dist/polyfill.js?03b9323c0501aae92009b27cf63cea3f4754b408:3911:29
base/node_modules/babel-polyfill/dist/polyfill.js?03b9323c0501aae92009b27cf63cea3f4754b408:3924:31
flush@base/node_modules/babel-polyfill/dist/polyfill.js?03b9323c0501aae92009b27cf63cea3f4754b408:1209:11


Suite: Async Functions
Description: mapAsync
Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
tryCatcher@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:19750:28
_settlePromiseFromHandler@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17772:35
_settlePromise@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17829:43
_settlePromise0@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17874:24
_settlePromises@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17953:33
_drainQueue@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:14682:31
_drainQueues@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:14692:21
drainQueues@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:14566:26
run@base/node_modules/babel-polyfill/dist/polyfill.js?03b9323c0501aae92009b27cf63cea3f4754b408:3911:29
base/node_modules/babel-polyfill/dist/polyfill.js?03b9323c0501aae92009b27cf63cea3f4754b408:3924:31
flush@base/node_modules/babel-polyfill/dist/polyfill.js?03b9323c0501aae92009b27cf63cea3f4754b408:1209:11


Suite: Async Functions
Description: mapValuesAsync
Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
tryCatcher@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:19750:28
_settlePromiseFromHandler@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17772:35
_settlePromise@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17829:43
_settlePromise0@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17874:24
_settlePromises@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:17953:33
_drainQueue@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:14682:31
_drainQueues@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:14692:21
drainQueues@base/test/async.spec.js?7be421777c8012617c66ca7025b99f5caacd00aa:14566:26
run@base/node_modules/babel-polyfill/dist/polyfill.js?03b9323c0501aae92009b27cf63cea3f4754b408:3911:29
base/node_modules/babel-polyfill/dist/polyfill.js?03b9323c0501aae92009b27cf63cea3f4754b408:3924:31
flush@base/node_modules/babel-polyfill/dist/polyfill.js?03b9323c0501aae92009b27cf63cea3f4754b408:1209:11

  </td>
    </tr>
  </tbody>
</table>



<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Messages</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:book:</td>
      <td>

  We were able to automatically fix some formatting issues in this PR for you!
  </td>
    </tr>
  </tbody>
</table>


### Some things that were possibly fixed:

- Code that could be fixed via the --fix flag
- Formatting that could be fixed by prettier

Take a look at this commit to see what happened in detail: 46b73abc717b3330a28334986bc621518884b7e5


And look at this wiki page to see the reasoning behind the ESLint rules: https://github.com/smartprocure/eslint-config-smartprocure/wiki/Rules-and-Why-We-Chose-Them
<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by daedalus28** [comment]
The big open question here is how deep we want to go on this because mapAsync opens up the door for async everything. It's useful in practice, but as mentioned in #84 it might make more sense as a `bluebird-fp` lib.

**Comment by daedalus28** [comment]
A potential alternative: https://runkit.com/daedalus28/flexible-flow-async

The main idea there is to avoid needing things like mapValuesAsync (and thus, eventually everySingleMethodAsync) by making the async flow smart enough to automatically leverage the basic primitives during the composition (e.g. automatically using Promise.all or Promise.props).

**Comment by daedalus28** [comment]
Closing in favor of #411

**Pull request closed without merging**
